=== madchops1/Wesley/admin/scripts/HtmlCssEditor0.2/csseditor/xml/css.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="css">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collections" />
        <xs:element ref="entry-lists" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="collections">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="collection" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="element" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="element">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entries" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="entries">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="list" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="entry" type="xs:string" />

  <xs:element name="entry-lists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry-list" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="entry-list">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="item" type="xs:string" />

</xs:schema>

=== madchops1/Wesley/admin/scripts/HtmlCssEditor0.2/csseditor/xml/css.xml
<?xml version="1.0" encoding="UTF-8"?>
<css xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="css.xsd">
  <collections>

    <collection name="Background">
      <group name="Background">
        <element name="background-attachment">
          <entries>
            <entry>scroll</entry>
            <entry>fixed</entry>
          </entries>
        </element>
        <element name="background-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
        <element name="background-image">
          <entries>
            <entry>file...</entry>
          </entries>
        </element>
        <element name="background-position">
          <entries>
            <entry>position...</entry>
            <entry>top left</entry>
            <entry>top center</entry>
            <entry>top right</entry>
            <entry>center left</entry>
            <entry>center center</entry>
            <entry>center right</entry>
            <entry>bottom left</entry>
            <entry>bottom center</entry>
            <entry>bottom right</entry>
          </entries>
        </element>
        <element name="background-repeat">
          <entries>
            <entry>repeat</entry>
            <entry>repeat-x</entry>
            <entry>repeat-y</entry>
            <entry>no-repeat</entry>
          </entries>
        </element>
      </group>
    </collection>

    <collection name="Border">
      <group name="Border">
        <element name="border-width">
          <entries>
            <entry>size...</entry>
            <entry>thin</entry>
            <entry>medium</entry>
            <entry>thick</entry>
          </entries>
        </element>
        <element name="border-style">
          <entries>
            <list>border-styles</list>
          </entries>
        </element>
        <element name="border-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
      </group>
      <group name="Border-top">
        <element name="border-top-width">
          <entries>
            <entry>size...</entry>
            <entry>thin</entry>
            <entry>medium</entry>
            <entry>thick</entry>
          </entries>
        </element>
        <element name="border-top-style">
          <entries>
            <list>border-styles</list>
          </entries>
        </element>
        <element name="border-top-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
      </group>
      <group name="Border-left">
        <element name="border-left-width">
          <entries>
            <entry>size...</entry>
            <entry>thin</entry>
            <entry>medium</entry>
            <entry>thick</entry>
          </entries>
        </element>
        <element name="border-left-style">
          <entries>
            <list>border-styles</list>
          </entries>
        </element>
        <element name="border-left-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
      </group>
      <group name="Border-bottom">
        <element name="border-bottom-width">
          <entries>
            <entry>size...</entry>
            <entry>thin</entry>
            <entry>medium</entry>
            <entry>thick</entry>
          </entries>
        </element>
        <element name="border-bottom-style">
          <entries>
            <list>border-styles</list>
          </entries>
        </element>
        <element name="border-bottom-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
      </group>
      <group name="Border-right">
        <element name="border-right-width">
          <entries>
            <entry>size...</entry>
            <entry>thin</entry>
            <entry>medium</entry>
            <entry>thick</entry>
          </entries>
        </element>
        <element name="border-right-style">
          <entries>
            <list>border-styles</list>
          </entries>
        </element>
        <element name="border-right-color">
          <entries>
            <entry>color...</entry>
            <list>colors</list>
          </entries>
        </element>
      </group>
    </collection>

    <collection name="Classification">
      <group name="Classification">
        <element name="clear">
          <entries>
            <entry>left</entry>
            <entry>right</entry>
            <entry>both</entry>
            <entry>none</entry>
          </entries>
        </element>
        <element name="curor">
          <entries>
            <entry>file...</entry>
            <entry>auto</entry>
            <entry>crosshair</entry>
            <entry>default</entry>
            <entry>pointer</entry>
            <entry>move</entry>
            <entry>e-resize</entry>
            <entry>ne-resize</entry>
            <entry>nw-resize</entry>
            <entry>n-resize</entry>
            <entry>se-resize</entry>
            <entry>sw-resize</entry>
            <entry>s-resize</entry>
            <entry>w-resize</entry>
            <entry>text</entry>
            <entry>wait</entry>
            <entry>help</entry>
          </entries>
        </element>
        <element name="display">
          <entries>
            <entry>none</entry>
            <entry>inline</entry>
            <entry>block</entry>
            <entry>list-item</entry>
            <entry>run-in</entry>
            <entry>compact</entry>
            <entry>marker</entry>
            <entry>table</entry>
            <entry>inline-table</entry>
            <entry>table-row-group</entry>
            <entry>table-header-group</entry>
            <entry>table-footer-group</entry>
            <entry>table-row</entry>
            <entry>table-column-group</entry>
            <entry>table-column</entry>
            <entry>table-cell</entry>
            <entry>table-caption</entry>
          </entries>
        </element>
        <element name="float">
          <entries>
            <entry>none</entry>
            <entry>left</entry>
            <entry>right</entry>
          </entries>
        </element>
        <element name="position">
          <entries>
            <entry>static</entry>
            <entry>relative</entry>
            <entry>absolute</entry>
            <entry>fixed</entry>
          </entries>
        </element>
        <element name="visibility">
          <entries>
            <entry>visible</entry>
            <entry>hidden</entry>
<!--        <entry>collapse</entry>     -->
          </entries>
        </element>
      </group>
    </collection>

    <collection name="Content">
      <group name="Content">
        <element name="content">
          <entries>
            <entry>file...</entry>
            <entry>string...</entry>
            <entry>open-quote</entry>
            <entry>close-quote</entry>
            <entry>no-open-quote</entry>
            <entry>no-close-quote</entry>
          </entries>
        </element>
        <element name="counter-increment">
          <entries>
            <entry>counter...</entry>
            <entry>none</entry>
          </entries>
        </element>
        <element name="counter-reset">
          <entries>
            <entry>counter...</entry>
            <entry>none</entry>
          </entries>
        </element>
        <element name="quotes">
          <entries>
            <entry>quotes...</entry>
            <entry>none</entry>
          </entries>
        </element>
      </group>
    </collection>

    <collection name="Dimension">
      <group name="Dimension">
        <element name="height">
          <entries>
            <entry>length...</entry>
            <entry>auto</entry>
          </entries>
        </element>
        <element name="width">
          <entries>
            <entry>length...</entry>
            <entry>auto</entry>
          </entries>
        </element>
        <element name="min-height">
          <entries>
            <entry>length...</entry>
          </entries>
        </element>
        <element name="min-width">
          <entries>
            <entry>length...</entry>
          </entries>
        </element>
        <element name="max-height">
          <entries>
            <entry>length...</entry>
            <entry>none</entry>
          </entries>
        </element>
        <element name="max-width">
          <entries>
            <entry>length...</entry>
            <entry>none</entry>
          </entries>
        </element>
        <element name="line-height">
          <entries>
            <entry>length...</entry>
            <entry>number...</entry>
            <entry>normal</entry>
          </entries>
        </element>
      </group>
    </collection>

    <collection name="Font">
      <group name="Font">
        <element name="font">
          <entries>
            <entry>caption</entry>
            <entry>icon</entry>
            <entry>menu</entry>
            <entry>message-box</entry>
            <entry>small-caption</entry>
            <entry>status-bar</entry>
          </entries>
        </element>
        <element name="font-family">
          <entries>
<!--        <entry>fonts...</entry> -->
            <list>font-family</list>
          </entries>
        </element>
        <element name="font-size">
          <entries>
            <entry>length...</entry>
